name: Release
on:
  push:
    branches: [ "main", "ci" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: source ci/release.sh
    - run: ls -la

    - uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports
        
